# This file is machine-generated - editing it directly is not advised

[[BandStruct]]
deps = ["ConstructionBase", "LinearAlgebra", "MLStyle", "Printf", "Random"]
path = "../BandStruct"
uuid = "839fd882-bd41-41b1-9826-d7cfd97ab335"
version = "0.1.0"

[[ConstructionBase]]
git-tree-sha1 = "a2a6a5fea4d6f730ec4c18a76d27ec10e8ec1c50"
uuid = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
version = "1.0.0"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[MLStyle]]
git-tree-sha1 = "c1f64c54a7e3a25723de44898b472fcd3be12bff"
uuid = "d8e11817-5142-5d16-987a-aa16d5891078"
version = "0.4.0"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
